version: '3'

services:
  mongo:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOTPASS}
    ports: 
      - '3306:3306'
    volumes:
      - type: bind
        source: ./sqlData
        target: /var/lib/mysql

volumes:
  sqlData:
